      save_best: True
      plot_agents: True

      logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./tqc_logs/
            verbose: False
            every_n_seconds: 10

      algorithm:
            seed: 1
            nb_seeds: 1
            n_envs: 8
            n_steps: 32
            max_grad_norm: 0.5
            buffer_size: 1e6
            batch_size: 256
            eval_interval: 2000
            nb_evals: 10
            learning_starts: 10000
            tau_target: 0.05
            top_quantiles_to_drop: 42
            max_epochs: 25000
            discount_factor: 0.98
            entropy_coef: 1e-7
            target_entropy: auto
            architecture:
                  actor_hidden_size: [32, 32]
                  critic_hidden_size: [256, 256]
                  n_nets: 2
                  n_quantiles: 25
      gym_env:
            classname: __main__.make_gym_env
            env_name: CartPoleContinuous-v1

      actor_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3

      critic_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3

      entropy_coef_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3