    save_best: False
    plot_agents: False

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./td3_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 1
      nb_seeds: 1
      max_grad_norm: 0.5
      buffer_size: 2e5
      n_envs: 1
      n_steps: 100
      batch_size: 64
      tau_target: 0.05
      eval_interval: 2000
      learning_starts: 10000
      nb_evals: 10
      gae: 0.8
      action_noise: 0.1
      max_epochs: 5000
      discount_factor: 0.98
      architecture:
        actor_hidden_size: [256, 256]
        critic_hidden_size: [256, 256]

    gym_env:
      classname: __main__.make_gym_env
      env_name: LunarLanderContinuous-v2

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 1e-4

    critic_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3
