    save_best: True
    plot_agents: True


    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./a2c_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 5
      n_envs: 8
      n_steps: 100
      eval_interval: 1000
      nb_evals: 10
      max_grad_norm: 0.5
      gae: 0.8
      max_epochs: 50000
      discount_factor: 0.95
      entropy_coef: 2.55e-7
      critic_coef: 0.4
      a2c_coef: 1
      actor_type: ConstantVarianceContinuousActor
      architecture:
        hidden_size: [64, 64]

    gym_env:
      classname: __main__.make_gym_env
      env_name: Pendulum-v1

    optimizer:
      classname: torch.optim.RMSprop
      lr: 0.004
